# Generated by Django 4.0.2 on 2022-02-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drgmik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
