# Generated by Django 4.0.2 on 2022-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drgmik', '0002_rename_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='heading',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
