# Generated by Django 4.0.2 on 2022-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drgmik', '0003_image_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
