# Generated by Django 4.0.2 on 2022-04-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drgmik', '0004_article_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='article',
            new_name='article_fk',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='article',
            new_name='article_fk',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='article',
            new_name='article_fk',
        ),
        migrations.AddField(
            model_name='article',
            name='cover_img_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='drgmik.image'),
            preserve_default=False,
        ),
    ]
