# Generated by Django 4.0.2 on 2022-04-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drgmik', '0005_rename_article_author_article_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='article_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drgmik.article'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='article_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drgmik.article'),
        ),
    ]
